global:
  max_process_concurrency: 3 # 1 - 65535: Cuantos procesos en simultaneo se pueden correr
  check_new_config_interval: 10 # 1 - 999999999 Cada cuantos segundos se vuelve a chequear la configuracion
  unknown_action: "PENDING" # PENDING|FAILED|SUCCESS : El estado que se le pone a las tareas que quedaron con estado unknown. El estado unknown se da cuando este servicio termina inesperadamente
  log_directory: "logs"
tasks: #importante nunca cambiar el ID de una tarea, sino se pierde su historia (o se mezcla con la de otro)
  - id: 1
    type: "oracle"
    command: "declare
      respuesta varchar2(32767);
      begin
      :respuesta := siper.fnc_test(1);
      end;"
    day: 14 #Que dia del mes corre
  - id: 2
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula2.sh" #podria ser un spark-submit
    day: 4
  - id: 3
    type: "oracle"
    command: "begin PRC_CALCULA3(); end;"
    day: 1
  - id: 4
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula4.sh" #podria ser un sqoop
    day: 15
  - id: 5
    type: "bash"
    command: "/home/matiaet98/test.sh"
    day: 14
  - id: 6
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula6.sh"
    day: 15
  - id: 7
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula7.sh"
    day: 15
  - id: 8
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula8.sh"
    day: 15
  - id: 9
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula9.sh"
    day: 15
  - id: 10
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula10.sh"
    day: 15
  - id: 11
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula11.sh"
    day: 15
  - id: 12
    type: "oracle"
    command: "declare
      respuesta varchar2(32767);
      begin
      :respuesta := siper.fnc_test(1);
      end;"
    day: 14
  - id: 13
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula12.sh"
    day: 15
  - id: 14
    type: "oracle"
    command: "declare
      respuesta varchar2(32767);
      begin
      :respuesta := siper.fnc_test(1);
      end;"
    day: 14
  - id: 15
    type: "bash"
    command: "/home/matiaet98/test2.sh"
    day: 14
  - id: 16
    type: "oracle"
    command: "declare
      respuesta varchar2(32767);
      begin
      :respuesta := siper.fnc_test(1);
      end;"
    day: 14
