global:
  max_process_concurrency: 5 # 1 - 65535: Cuantos procesos en simultaneo se pueden correr
  check_new_config_interval: 1 # 1 - 999999999 Cada cuantos segundos se vuelve a chequear la configuracion
  unknown_action: "PENDING" # PENDING|FAILED|SUCCESS : El estado que se le pone a las tareas que quedaron con estado unknown. El estado unknown se da cuando este servicio termina inesperadamente
  pid_directory: "$HOME"
  log_directory: "$HOME/logs"
oracle:
  fisco_connection_string: "(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=ORCLPDB1.localdomain)))"
  misg_connection_string: "(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=ORCLPDB1.localdomain)))"
  etl_user: "FISCA_ETL"
  etl_password: "FISCA_ETL"
tasks: #importante nunca cambiar el ID de una tarea, sino se pierde su historia (o se mezcla con la de otro)
  - id: 1
    type: "oracle"
    command: "begin PRC_CALCULA1('hello'); end;"
    day: 1 #Que dia del mes corre
  - id: 2
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula2.sh" #podria ser un spark-submit
    day: 1
  - id: 3
    type: "oracle"
    command: "begin PRC_CALCULA3(); end;"
    day: 1
  - id: 4
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula4.sh" #podria ser un sqoop
    day: 5
