global:
  max_process_concurrency: 3 # 1 - 65535: Cuantos procesos en simultaneo se pueden correr
  check_new_config_interval: 10 # 1 - 999999999 Cada cuantos segundos se vuelve a chequear la configuracion
  log_directory: "./logs"
tasks: #importante nunca cambiar el ID de una tarea, sino se pierde su historia (o se mezcla con la de otro)
  - id: 1
    type: "oracle"
    command: "declare
      respuesta varchar2(32767);
      begin
      :respuesta := siper.fnc_test(1);
      end;"
  - id: 2
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula2.sh" #podria ser un spark-submit
    depends: 
      - 1
  - id: 3
    type: "oracle"
    command: "begin PRC_CALCULA3(); end;"
    depends:
      - 1
  - id: 4
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula4.sh" #podria ser un sqoop
    depends:
      - 3
      - 2
  - id: 5
    type: "bash"
    command: "/home/matiaet98/test.sh"
    depends:
      - 2
  - id: 6
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula6.sh"
    depends:
      - 1
      - 3
  - id: 7
    type: "bash"
    command: "/usr/local/siper/ingestion/calcula7.sh"