SET DEFINE OFF;
CREATE USER "MFLOW" IDENTIFIED BY "MFLOW";
GRANT "CONNECT" TO "MFLOW" ;
GRANT "RESOURCE" TO "MFLOW" ;
ALTER USER "MFLOW" QUOTA UNLIMITED ON "USERS";
CREATE SEQUENCE  "MFLOW"."SEQ_TASKS_MASTER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 124 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE TABLE "MFLOW"."TASKS" ("ID_MASTER" NUMBER, "ID_TASK" VARCHAR2(4000), "START_DATE" DATE, "END_DATE" DATE, "STATUS" VARCHAR2(20)) ;
COMMENT ON COLUMN "MFLOW"."TASKS"."STATUS" IS 'SUCCESS / FAILED / RUNNING / NONE';
CREATE TABLE "MFLOW"."TASKS_MASTER" ("ID" NUMBER, "START_DATE" DATE, "END_DATE" DATE, "STATUS" VARCHAR2(20)) ;
COMMENT ON COLUMN "MFLOW"."TASKS_MASTER"."STATUS" IS 'STARTED / ENDED';
CREATE UNIQUE INDEX "MFLOW"."ID_TASKS_MASTER_PK1" ON "MFLOW"."TASKS_MASTER" ("ID") ;
CREATE INDEX "MFLOW"."TASKS_PK2" ON "MFLOW"."TASKS" ("ID_TASK") ;
CREATE INDEX "MFLOW"."TASKS_PK1" ON "MFLOW"."TASKS" ("ID_MASTER") ;

ALTER TABLE "MFLOW"."TASKS" MODIFY ("ID_MASTER" NOT NULL ENABLE);
ALTER TABLE "MFLOW"."TASKS" MODIFY ("ID_TASK" NOT NULL ENABLE);
ALTER TABLE "MFLOW"."TASKS" MODIFY ("START_DATE" NOT NULL ENABLE);
ALTER TABLE "MFLOW"."TASKS" MODIFY ("STATUS" NOT NULL ENABLE);

ALTER TABLE "MFLOW"."TASKS_MASTER" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "MFLOW"."TASKS_MASTER" MODIFY ("START_DATE" NOT NULL ENABLE);
ALTER TABLE "MFLOW"."TASKS_MASTER" MODIFY ("STATUS" NOT NULL ENABLE);
